name: 编译BabySafe

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: 下载源码
      uses: actions/checkout@v4

    - name: 安装编译环境
      run: |
        choco install mingw -y

    - name: 编译游戏
      run: |
        g++ src/main.cpp src/adb.cpp src/action.cpp src/config.cpp -o BabySafe.exe -static

    - name: 整理游戏文件
      run: |
        mkdir release
        copy BabySafe.exe release\
        copy config.ini release\
        xcopy 级别 release\级别 /E /I

    - name: 保存完整游戏
      uses: actions/upload-artifact@v4
      with:
        name: BabySafe完整游戏
        path: release
